server:
  port: 8110

spring:
  profiles:
    active: dev
  application:
    name: service-est
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcsdata?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.101.58:3306/tcsdata?serverTimezone=GMT%2B8
#    username: root
#    password: tcbigdata
#    url: jdbc:mysql://192.168.1.91:3306/db2063_pa_est?serverTimezone=GMT%2B8
#    username: root
#    password: root
  #spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  servlet:
    multipart:
      max-request-size: 100000000
      max-file-size: 100000000
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/cloudera/poverty/mapper/xml/*.xml